# Generated by Django 2.2.5 on 2026-06-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='abacatepay_billing_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deposito',
            name='abacatepay_checkout_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
